**Axis wise operation**



running vertically downwards across rows (axis 0),

and the second running horizontally across columns (axis 1).

In [1]:
import numpy as np
a=np.array(np.arange(1,45,5).reshape(3,3))
print(a,'\n')
print(a.sum(),'sum of all values \n')# prints sum of all values
print(a.sum(axis=0),'sum row wise \n')
print(a.sum(axis=1),'sum column wise \n')

[[ 1  6 11]
 [16 21 26]
 [31 36 41]] 

189 sum of all values 

[48 63 78] sum row wise 

[ 18  63 108] sum column wise 



In [2]:
print(a,'\n')
print(a.mean(),' mean of all values \n')# prints sum of all values
print(a.mean(axis=0),'mean row wise \n')
print(a.mean(axis=1),' Mean column wise \n')

[[ 1  6 11]
 [16 21 26]
 [31 36 41]] 

21.0  mean of all values 

[16. 21. 26.] mean row wise 

[ 6. 21. 36.]  Mean column wise 



**Stacking**

numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")


Join a sequence of arrays along an existing axis.

T in Python is used to obtain the transpose of a given array. Transpose: The transpose of a matrix is the process of interchanging the row of a matrix with the column and vice-versa.

In [3]:
# we can use concatenate(),to add the two arrays but the shape should align for code to execute
import numpy as np
a=np.array([[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]])
b=np.array([[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1]])
print(np.concatenate((a, b), axis=0),'axis=0 row wise','\n')# adds the other array row wise
print(np.concatenate((a, b), axis=1),'axis=1 column wise','\n')

b1=np.array([[1,1,1,1,1]])
print(np.concatenate((a, b1.T), axis=1),'axis=1 column wise same number of columns different row number use T Transpose','\n')
print(np.concatenate((a, b), axis=None),'axis=o results in 1-D array','\n')


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] axis=0 row wise 

[[0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 1 1 1 1 1]] axis=1 column wise 

[[0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]
 [0 0 0 0 0 1]] axis=1 column wise same number of columns different row number use T Transpose 

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1] axis=o results in 1-D array 



**Ravel**

flattens any array to a 1-d array

In [4]:
print(a.ravel())
print(a.reshape(-1))# can also use reshape to flatten

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


**Split**

splits array into equal number of arrays

In [5]:
a1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.split(a1,2),"splits into two \n")
print(np.split(a1,5,axis=1),'each column gets separated \n')


[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])] splits into two 

[array([[1],
       [6]]), array([[2],
       [7]]), array([[3],
       [8]]), array([[4],
       [9]]), array([[ 5],
       [10]])] each column gets separated 



In [6]:
a2=np.array([[[1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5]],

             [[2,2,2,2,2],
             [2,2,2,2,2],
             [2,2,2,2,2]],

             np.full((3,5),3)])
print(a2,'\n')
print(np.split(a2,3,axis=0),'\n')
print(np.hsplit(a2,3),'\n Takes each row from 2-d arrays inside 3-d array')
print(np.vsplit(a2,3),'\n Takes each block')

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[2 2 2 2 2]
  [2 2 2 2 2]
  [2 2 2 2 2]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]] 

[array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]]), array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]]), array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])] 

[array([[[1, 2, 3, 4, 5]],

       [[2, 2, 2, 2, 2]],

       [[3, 3, 3, 3, 3]]]), array([[[1, 2, 3, 4, 5]],

       [[2, 2, 2, 2, 2]],

       [[3, 3, 3, 3, 3]]]), array([[[1, 2, 3, 4, 5]],

       [[2, 2, 2, 2, 2]],

       [[3, 3, 3, 3, 3]]])] 
 Takes each row from 2-d arrays inside 3-d array
[array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]]), array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]]), array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])] 
 Takes each block


In [10]:
arr=np.array([[1,2,3],[1,2,3]])
arr.T
arr3=np.array([[[1,2,3],
               [1,2,3]],
              [[1,2,3],[1,2,3]
               ]])
print(arr3,'\n')
print(arr3.T)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]] 

[[[1 1]
  [1 1]]

 [[2 2]
  [2 2]]

 [[3 3]
  [3 3]]]


**numpy.stack**


numpy.stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')


Join a sequence of arrays along a new axis.

The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension.

In [15]:
# input array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
c1 = np.stack((a, b),axis=1)
print(c,'\n \n',c1,'\n \n')
#stacking 2 arrays along -1 axis
c2=np.stack((a,b),axis=-1)
print(c2)

[[1 2 3]
 [4 5 6]] 
 
 [[1 4]
 [2 5]
 [3 6]] 
 

[[1 4]
 [2 5]
 [3 6]]


**numpy.hstack()** function is used to stack the sequence of input arrays horizontally (i.e. column wise) to make a single array.


Syntax : numpy.hstack(tup)

Parameters : tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same shape along all but the second axis. Return : [stacked ndarray] The stacked array of the input arrays.

In [31]:
# making 3 arrays to perform stack
arr1=np.arange((9)).reshape(9)
arr1d=arr1
arr2=np.full((3,3),2,dtype=int)
arr2d=arr2
arr3=np.arange((27),dtype=int).reshape(3,3,3)
arr3d=arr3

In [33]:
print(arr1,'\n','\n 1d array')
print(arr2,'\n','\n 2d array')
print(arr3,'\n','\n 3d array')


[0 1 2 3 4 5 6 7 8] 
 
 1d array
[[2 2 2]
 [2 2 2]
 [2 2 2]] 
 
 2d array
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 
 
 3d array


In [34]:
print(np.hstack((arr1, arr1d)),'\n ')
print(np.vstack((arr1,arr1d)))

[0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8] 
 
[[0 1 2 3 4 5 6 7 8]
 [0 1 2 3 4 5 6 7 8]]


In [35]:
print(np.hstack((arr2,arr2d)),'\n')
print(np.vstack((arr2,arr2d)),'\n')

[[2 2 2 2 2 2]
 [2 2 2 2 2 2]
 [2 2 2 2 2 2]] 

[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]] 



In [40]:
print(np.hstack((arr3,arr3d)),'\n Hstack')
print(np.vstack((arr3,arr3d)),'\n Vstack')
vstack=np.vstack((arr3,arr3d))
print(vstack.shape,'vstack shape')
hstack=np.hstack((arr3,arr3d))
print(hstack.shape,'hstack shape')


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]
  [18 19 20]
  [21 22 23]
  [24 25 26]]] 
 Hstack
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]

 [[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 
 Vstack
(6, 3, 3) vstack shape
(3, 6, 3) hstack shape


**Random**

In [41]:
# randn() gives random values with normal distribution
r1=np.random.randn(3,3)
r1

array([[ 0.39880517, -0.63951773, -0.64379356],
       [-0.22951623, -1.66690254, -2.17849265],
       [-0.49333338,  0.25847501, -0.1436023 ]])

In [45]:
# sample() gives unifromly distributed data between 0 and 1
r2=np.random.sample((3,3))
r2

array([[0.54120286, 0.31682929, 0.05611928],
       [0.64362285, 0.17373993, 0.95533871],
       [0.10561406, 0.19528939, 0.89450853]])

In [48]:
# randint gives random values that are integer between a specified start and end position
r3=np.random.randint(10,30,(3,3))
r3

array([[10, 16, 11],
       [15, 27, 24],
       [28, 29, 10]])

In [51]:
# get random number from a list or tuple
x = np.random.choice([3, 5, 7, 9])

print(x)

3


In [53]:
# can also make an array using choice
x = np.random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 9 7 3 5]
 [3 3 9 5 3]
 [5 7 9 7 9]]


# Seed

The numpy random **seed** is a numerical value that generates a new set or repeats pseudo-random numbers. The value in the numpy random seed saves the state of randomness. If we call the seed function using value 1 multiple times, the computer displays the same random numbers.

In [57]:
np.random.seed(1)
a=np.random.randint(10,50,(3,6))
print(a)

[[47 22 18 19 21 15]
 [25 10 26 11 22 17]
 [16 35 30 47 28 30]]
